services:
  - type: web
    name: earnedclub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: earnedclub.club,www.earnedclub.club,earnedclub.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://earnedclub.club,https://www.earnedclub.club,https://earnedclub.onrender.com
      - key: SITE_URL
        value: https://earnedclub.club
      - key: DATABASE_URL
        sync: false
