from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("test/", views.level_test, name="level_test"),
    path("sitemap.xml", views.sitemap_xml, name="sitemap_xml"),
    path("sitemap.xsl", views.sitemap_xsl, name="sitemap_xsl"),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/submissions/<int:submission_id>/proof/", views.add_submission_proof, name="add_submission_proof"),
    path("dashboard/submissions/<int:submission_id>/delete/", views.delete_submission, name="delete_submission"),
    path("dashboard/goals/<int:goal_id>/delete/", views.delete_goal, name="delete_goal"),
    path("dashboard/workouts/<int:workout_id>/duplicate/", views.duplicate_workout, name="duplicate_workout"),
    path("dashboard/workouts/quick-add-last/", views.quick_add_last_workout, name="quick_add_last_workout"),
    path("workouts/", views.workouts, name="workouts"),
    path("workouts/start/", views.start_workout, name="start_workout"),
    path("workouts/sessions/<int:session_id>/", views.workout_session_detail, name="workout_session_detail"),
    path("workouts/sessions/<int:session_id>/finish/", views.finish_workout_session, name="finish_workout_session"),
    path("workouts/sessions/<int:session_id>/exercise/<int:exercise_id>/", views.update_workout_session, name="update_workout_session"),
    path("workouts/<int:workout_id>/delete/", views.delete_workout, name="delete_workout"),
    path("workouts/<int:workout_id>/highlight/", views.toggle_highlight_workout, name="toggle_highlight_workout"),
    path("admin-review/", views.admin_review, name="admin_review"),
    path("admin-review/<int:submission_id>/", views.review_submission, name="review_submission"),
    path("content-engine-admin/", views.content_engine_admin, name="content_engine_admin"),
    path("profiles/", views.profiles, name="profiles"),
    path("athlete/<slug:slug>/", views.athlete_profile, name="athlete_profile"),
    path("athlete/<slug:slug>/follow/", views.toggle_follow, name="toggle_follow"),
    path("athlete/<slug:slug>/<str:kind>/", views.social_list, name="social_list"),
    path("comparison/<slug:left>vs<slug:right>/", views.comparison, name="comparison"),
    path("workout/<slug:slug>/", views.workout_detail, name="workout_detail"),
    path("challenge/", views.challenge, name="challenge"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    path("calculators/", views.calculators, name="calculators"),
    path("newsletter-signup/", views.newsletter_signup, name="newsletter_signup"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
]
