# Generated by Django 5.2.13 on 2026-04-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-reps', 'created_at')},
        ),
    ]
