# Generated by Django 5.2.13 on 2026-04-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='video_file',
            field=models.FileField(blank=True, upload_to='submission_videos/'),
        ),
    ]
