# Generated by Django 5.2.13 on 2026-04-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_submission_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_storage_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='video_storage_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
