# Generated by Django 5.2.13 on 2026-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20260427_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='highlighted_on_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='body_part',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('mobility', 'Mobility')], default='strength', max_length=24),
        ),
    ]
