# Generated by Django 5.2.13 on 2026-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_workout_highlighted_on_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
