# Generated by Django 5.2.13 on 2026-05-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_repair_submission_discipline_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('pushups', 'Push-up target'), ('pullups', 'Pull-up target'), ('run_5k', '5K target'), ('run_10k', '10K target'), ('hybrid_score', 'Hybrid Score target'), ('rank', 'Rank target')], default='pushups', max_length=16),
        ),
    ]
